name: Deploy React CD with actions

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Comprobacion
        uses: actions/checkout@master

      - name: Create Node Eviroment
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Instalar y Compilar
        run: npm install && npm run build

      - name: Despliegue
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: build
      