name: Deploy React CD with actions

on:
  push:
    branches:
      - master



jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Comprobacion
        uses: actions/checkout@master

      - name: Instalar y Compilar
        run: npm install && npm run build

      - name: Despliegue
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: build
      